volumes:
    db:

services:
  # db:
  #   image: postgres:15
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - "db:/var/lib/postgresql/data"

  buzzer:
    build: .
    volumes:
      - .:/rails
    command: sh -c "rm -f tmp/pids/server.pid && exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000

